# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b1f9d52edfe9e4de7de61262e13b08c2cd29127d3ce0f9507f5fdcaa9adb8655114a51df1c94fd71db53b82e44123fde7688cbd4fd5c41994fabf0593425572

test:
  secret_key_base: 54b5e1ed17e406c5c67f2433b614d66e023ef1bd0c73e98660dae733263f62837b50fb8bbc58e9369ee258cb9ae745f88f9ad8ff41a4d310f6c7a786c95740dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
